about:
  my_name: Arin Suga
  sex: Male
  job_title: Application Consultant
  nationality: Indonesia
contact:
  mail: arinsuga@gmail.com
  website: https://arinsuga.github.io/
  linkedin: https://www.linkedin.com/in/arin-suga-941076a5/
  github: https://github.com/arinsuga/
