about:
  my_name: ARIN SUGA
  sex: Male
  job_title: Application Consultant
  nationality: Indonesia
  mail: arinsuga@gmail.com
  website1: https://arinsuga.github.io/
  website2: https://sugaprivate.github.io/

