about:
  my_name: ARIN SUGA
  sex: Male
  job_title: Application Consultant
  nationality: Indonesia
contact:
  mail: arinsuga@gmail.com
  website: https://arinsuga.github.io/
  github: https://github.com/arinsuga/

